# Generated by Django 5.1.4 on 2024-12-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_item_delete_choice_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
